# ✦ Nexora.AI

### Create Smarter. Build Faster. With AI.

Nexora.AI is a full-stack AI-powered creative workspace that brings content generation, image creation, image editing, resume analysis, and community sharing into one platform.

<p align="left">

![React](https://img.shields.io/badge/React-Frontend-61DAFB?logo=react&logoColor=white)
![Node.js](https://img.shields.io/badge/Node.js-Backend-339933?logo=node.js&logoColor=white)
![Express](https://img.shields.io/badge/Express-API-000000?logo=express&logoColor=white)
![PostgreSQL](https://img.shields.io/badge/PostgreSQL-Neon-4169E1?logo=postgresql&logoColor=white)
![Cloudinary](https://img.shields.io/badge/Cloudinary-Media-3448C5?logo=cloudinary&logoColor=white)
![Netlify](https://img.shields.io/badge/Netlify-Deployed-00C7B7?logo=netlify&logoColor=white)

</p>

---

## 🌐 Live Demo

The application is deployed and available here:

### [🚀 Open Nexora.AI](https://nexona-ai.netlify.app/)

---

## 📌 Overview

**Nexora.AI** is an AI SaaS application designed to simplify common creative and professional tasks.

Instead of using multiple applications for writing, generating images, editing images, and reviewing resumes, users can access all of these capabilities from a single dashboard.

The application is built using the **PERN stack**:

```text
PostgreSQL + Express.js + React.js + Node.js
```

It also integrates third-party services such as:

- OpenAI for AI-powered generation
- Cloudinary for image storage and AI image transformations
- Clerk for authentication and user management
- Neon for serverless PostgreSQL hosting

---

# ✨ Features

## 🤖 AI Tools

| Tool | Description |
|---|---|
| ✍️ **Write Article** | Generate structured articles using a topic and user-defined parameters |
| #️⃣ **Blog Titles** | Generate creative and engaging blog title suggestions |
| 🎨 **Generate Images** | Convert text prompts into AI-generated images |
| 🪄 **Remove Background** | Automatically remove the background from an uploaded image |
| ✂️ **Remove Object** | Remove unwanted objects from an image using AI |
| 📄 **Review Resume** | Upload a PDF resume and receive AI-powered feedback and suggestions |

---

## 👤 User Features

### Secure Authentication

Authentication and user sessions are handled using **Clerk**.

Protected application routes verify the authenticated user before allowing access to AI services.

---

### 📊 Personal Dashboard

Users get a centralized dashboard where they can:

- Access all AI tools
- View their active plan
- Track generated creations
- View recent activity
- Navigate between different AI services

---

### 🌍 Community

Users can explore publicly shared AI-generated creations through the community section.

This allows users to discover content generated by other users of the platform.

---

### 📱 Responsive Interface

The frontend is built using **React and Tailwind CSS** and is designed to work across:

- Desktop
- Laptop
- Tablet
- Mobile

---

# 🧰 Tech Stack

## Frontend

| Technology | Purpose |
|---|---|
| **React.js** | Building the user interface |
| **Vite** | Frontend development and build tool |
| **Tailwind CSS** | Responsive UI styling |
| **React Router DOM** | Client-side routing |
| **Axios** | Communication with backend APIs |
| **Lucide React** | UI icons |
| **React Hot Toast** | Notifications |
| **React Markdown** | Rendering AI-generated Markdown |
| **Clerk React** | Authentication and user sessions |

---

## Backend

| Technology | Purpose |
|---|---|
| **Node.js** | JavaScript runtime |
| **Express.js** | REST API and backend routing |
| **PostgreSQL** | Relational database |
| **Neon** | Serverless PostgreSQL hosting |
| **OpenAI API** | AI-powered content/image generation |
| **Cloudinary** | Image storage and AI image transformations |
| **Multer** | Handling uploaded files |
| **PDF Parse** | Extracting text from resume PDFs |
| **CORS** | Frontend-backend communication |

---

# 🏗️ Architecture

```text
                         ┌─────────────────┐
                         │     User        │
                         └────────┬────────┘
                                  │
                                  ▼
                         ┌─────────────────┐
                         │ React Frontend  │
                         │    Nexora.AI    │
                         └────────┬────────┘
                                  │
                              REST API
                                  │
                                  ▼
                         ┌─────────────────┐
                         │ Express Backend │
                         └────────┬────────┘
                                  │
                ┌─────────────────┼─────────────────┐
                │                 │                 │
                ▼                 ▼                 ▼
        ┌──────────────┐   ┌────────────┐   ┌────────────┐
        │    Clerk     │   │  OpenAI    │   │ Cloudinary │
        │     Auth     │   │    API     │   │ Image AI   │
        └──────────────┘   └────────────┘   └────────────┘
                                  │
                                  ▼
                         ┌─────────────────┐
                         │ Neon PostgreSQL │
                         │    Database     │
                         └─────────────────┘
```

---

# 🔄 Application Flow

A normal AI request follows this flow:

```text
User
  ↓
React Frontend
  ↓
API Request
  ↓
Clerk Authentication
  ↓
Express Middleware
  ↓
AI Controller
  ↓
OpenAI / Cloudinary
  ↓
Result Generated
  ↓
Save Creation in PostgreSQL
  ↓
Return Response
  ↓
Display Result to User
```

---

# 🖼️ Image Editing Flow

Nexora.AI uses **Cloudinary AI transformations** for its image editing capabilities.

## Remove Background

```text
Upload Image
     ↓
Multer
     ↓
Express Controller
     ↓
Cloudinary Upload
     ↓
Background Removal AI
     ↓
Processed Image URL
     ↓
Save to PostgreSQL
     ↓
Display Result
```

Cloudinary automatically detects the main subject and removes the surrounding background.

---

## Remove Object

The user uploads an image and specifies the object they want to remove.

```text
Image + Object Name
        ↓
      Multer
        ↓
 Upload to Cloudinary
        ↓
     public_id
        ↓
 gen_remove transformation
        ↓
 Cloudinary Generative AI
        ↓
   Processed Image
        ↓
      Result
```

Cloudinary removes the specified object and reconstructs the missing portion using the surrounding image context.

---

# 📄 Resume Review Flow

```text
Upload Resume PDF
        ↓
      Multer
        ↓
    PDF Parser
        ↓
 Extract Resume Text
        ↓
      AI Model
        ↓
 Analyse Resume
        ↓
 Feedback + Suggestions
        ↓
 Display to User
```

The tool can provide feedback on areas such as resume structure, skills, content quality, and possible improvements.

---

# 📁 Project Structure

```text
Nexora.AI/
│
├── client/
│   ├── src/
│   │
│   ├── assets/
│   │
│   ├── components/
│   │   ├── AITools.jsx
│   │   ├── CreationItem.jsx
│   │   ├── Footer.jsx
│   │   ├── Hero.jsx
│   │   ├── Navbar.jsx
│   │   ├── Plan.jsx
│   │   ├── Sidebar.jsx
│   │   └── Testimonial.jsx
│   │
│   ├── pages/
│   │   ├── BlogTitles.jsx
│   │   ├── Community.jsx
│   │   ├── Dashboard.jsx
│   │   ├── GenerateImages.jsx
│   │   ├── Home.jsx
│   │   ├── Layout.jsx
│   │   ├── RemoveBackground.jsx
│   │   ├── RemoveObject.jsx
│   │   ├── ReviewResume.jsx
│   │   └── WriteArticle.jsx
│   │
│   └── package.json
│
├── server/
│   │
│   ├── configs/
│   │   ├── cloudinary.js
│   │   ├── db.js
│   │   └── multer.js
│   │
│   ├── controllers/
│   │   ├── aiController.js
│   │   └── userController.js
│   │
│   ├── middlewares/
│   │   └── auth.js
│   │
│   ├── routes/
│   │   ├── aiRoutes.js
│   │   └── userRoutes.js
│   │
│   ├── server.js
│   └── package.json
│
└── README.md
```

---

# 🔌 API Overview

## AI Routes

Base route:

```http
/api/ai
```

Main operations include:

```http
POST /write-article
POST /generate-titles
POST /generate-image
POST /remove-background
POST /remove-object
POST /review-resume
```

These routes are responsible for the application's AI functionality.

---

## User Routes

Base route:

```http
/api/users
```

User-related functionality includes:

```http
GET  /profile
GET  /creations
POST /creations
GET  /community
```

Protected routes use authentication middleware to verify the current user.

---

# 🔐 Authentication Flow

```text
User Login
    ↓
Clerk
    ↓
Authentication Token
    ↓
Frontend API Request
    ↓
Express Auth Middleware
    ↓
Verify User
    ↓
Controller
    ↓
Protected Resource
```

This prevents unauthenticated users from accessing protected AI functionality.

---

# 🗄️ Database

The project uses **PostgreSQL hosted on Neon**.

The database stores information such as:

- User-related creation data
- AI-generated content
- Generated image URLs
- Creation metadata
- Public/private creation status

The application communicates with PostgreSQL through the backend rather than directly from the React frontend.

---

# ⚙️ Getting Started

## Prerequisites

Make sure you have:

```text
Node.js 18+
npm
Neon PostgreSQL account
Clerk account
Cloudinary account
OpenAI API credentials
```

---

## 1. Clone the Repository

```bash
git clone https://github.com/Pawankumar1188/QuickAiFrontend.git
cd QuickAiFrontend
```

---

## 2. Install Frontend Dependencies

```bash
cd client
npm install
```

---

## 3. Install Backend Dependencies

Open another terminal:

```bash
cd server
npm install
```

---

# 🔑 Environment Variables

Never commit your real `.env` files or API keys to GitHub.

## Client

Create:

```text
client/.env
```

Add:

```env
VITE_CLERK_PUBLISHABLE_KEY=your_clerk_publishable_key
VITE_API_BASE_URL=http://localhost:5000
```

---

## Server

Create:

```text
server/.env
```

Add:

```env
OPENAI_API_KEY=your_openai_api_key

CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name
CLOUDINARY_API_KEY=your_cloudinary_api_key
CLOUDINARY_API_SECRET=your_cloudinary_api_secret

DATABASE_URL=your_neon_postgresql_connection_string

CLERK_SECRET_KEY=your_clerk_secret_key

PORT=5000
```

---

# ▶️ Run Locally

## Start Backend

```bash
cd server
npm run server
```

The backend will run on:

```text
http://localhost:5000
```

---

## Start Frontend

Open another terminal:

```bash
cd client
npm run dev
```

Vite will provide a development URL such as:

```text
http://localhost:5173
```

---

# 🚀 Deployment

## Frontend

The Nexora.AI frontend is deployed using **Netlify**.

Live application:

### https://nexona-ai.netlify.app/

Production environment variables should be configured through the Netlify dashboard rather than committed to GitHub.

---

## Database

The PostgreSQL database is hosted using **Neon Serverless PostgreSQL**.

```text
Application
    ↓
Express Backend
    ↓
Neon PostgreSQL
```

---

## Media Storage

Uploaded and processed images are handled using **Cloudinary**.

Cloudinary provides:

- Cloud image storage
- CDN delivery
- Background removal
- Generative object removal
- Image transformations

---

# 🔒 Security

The application follows several basic security practices:

- Authentication using Clerk
- Protected backend routes
- Environment variables for API credentials
- Server-side database access
- Controlled file uploads using Multer
- CORS configuration
- Cloud-based image storage instead of storing uploads permanently on the application server

> API keys and database credentials should never be committed to the repository.

---

# 🎯 Future Improvements

Possible improvements for Nexora.AI include:

- AI generation credit system
- User favorites
- Advanced creation history
- Before/after image comparison
- Drag-and-drop image uploads
- Dark mode
- Admin analytics dashboard
- Usage monitoring
- Rate limiting
- Additional AI image editing tools

---

# 👨‍💻 Author

**Pawan Kumar**

Full-stack development • AI integration • Generative AI

---

# ⭐ Support

If you find Nexora.AI useful, consider giving the repository a ⭐ on GitHub.

---

<p align="center">

### ✦ Nexora.AI

**Create Smarter. Build Faster. With AI.**

</p>
